# Generated by Django 4.2.1 on 2023-06-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservation', '0012_remove_vol_compagnie_remove_vol_nombre_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vol',
            name='compagnie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='compagnie', to='app_reservation.compagnie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vol',
            name='image',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vol',
            name='nombre_place',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vol',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=(), max_digits=10),
            preserve_default=False,
        ),
    ]
