# Generated by Django 4.2.1 on 2023-06-14 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservation', '0013_vol_compagnie_vol_image_vol_nombre_place_vol_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationVol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reservation.utilisateur')),
                ('vol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reservation.vol')),
            ],
        ),
        migrations.RemoveField(
            model_name='location_voiture',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='location_voiture',
            name='voiture',
        ),
        migrations.RemoveField(
            model_name='reservation_vol',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='reservation_vol',
            name='vol',
        ),
        migrations.RemoveField(
            model_name='reservations_hotel',
            name='chambre',
        ),
        migrations.RemoveField(
            model_name='reservations_hotel',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='Chambre',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Location_Voiture',
        ),
        migrations.DeleteModel(
            name='Reservation_Vol',
        ),
        migrations.DeleteModel(
            name='Reservations_Hotel',
        ),
        migrations.DeleteModel(
            name='Voiture',
        ),
    ]
