# Generated by Django 4.2.1 on 2023-06-14 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservation', '0014_reservationvol_remove_location_voiture_utilisateur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_chambre', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_place', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id_hotel', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('code_pays', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location_Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField()),
                ('date_restitution', models.DateTimeField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur3', to='app_reservation.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation_Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur', to='app_reservation.utilisateur')),
                ('vol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vol', to='app_reservation.vol')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations_Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField()),
                ('date_restitution', models.DateTimeField()),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambre', to='app_reservation.chambre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur2', to='app_reservation.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=255)),
                ('modele', models.CharField(max_length=255)),
                ('localisation', models.CharField(max_length=255)),
                ('annee', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_place', models.IntegerField()),
                ('photo', models.CharField(max_length=255)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ReservationVol',
        ),
        migrations.AddField(
            model_name='location_voiture',
            name='voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voiture', to='app_reservation.voiture'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='app_reservation.hotel'),
        ),
    ]
