# Generated by Django 4.2.1 on 2023-06-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_reservation", "0016_remove_location_voiture_disponible_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location_voiture",
            name="paiement",
            field=models.BooleanField(default=False),
        ),
    ]
